import { VehicleBooking } from '../../src/interfaces/VehicleBooking';
import { getMockVtBooking } from './mVtBookings';

export function getMockVehicleBooking(i: number): VehicleBooking {
  switch (i) {
    case 1:
      const nonTrailerVtBooking = getMockVtBooking(1);
      return <VehicleBooking>{
        AXLE_SUPLM_AMT: 0,
        CANCELLATION_DATE: "to_date('0001-01-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss')",
        COMBI_NUM: 1,
        COUNTED_AXLES: 5,
        CUST_ACCT_PMNT_MKR: 1,
        DANG_GOODS_SWTCH: 'N',
        FEE_PAID: 0,
        FEE_REQUIRED: 0,
        FEE_UNDR_OVR_MRKR: 'N',
        FK_ACCT_ACCT_NO: '74926',
        FK_APPTYP_APPL_TYP: 'AAV',
        FK_BKGHDR2_NO: null,
        FK_BKGHDR2_USER_LO: null,
        FK_BKGHDR2_USER_NO: null,
        FK_BKGHDR_NO: 321,
        FK_BKGHDR_USER_LOC: 999,
        FK_BKGHDR_USER_NO: 'XR',
        FK_LANTBD_DATE: `to_date('${nonTrailerVtBooking.testDate}', 'yyyy-mm-dd')`,
        FK_LANTBD_OPEN_TIM: `to_date('${nonTrailerVtBooking.timeband.openTime}', 'yyyy-mm-dd hh24:mi:ss')`,
        FK_STATN_ID: 'P12345',
        FK_TBDPOS_ST_TIME: `to_date('${nonTrailerVtBooking.testTime}', 'yyyy-mm-dd hh24:mi:ss')`,
        FK_TSLANE_NO: 6,
        FK_VEHBKG2_COMBI: null,
        FK_VEHBKG2_NO: null,
        FK_VEH_SYST_NO: 1234567,
        LOCN_SUPLM_AMT: 0,
        NO_OF_AXLES: 5,
        OOH_SUPLM_AMT: 0,
        OUT_OF_HOURS_MKR: 'N',
        PREV_FEE_SWTCH: 'Y',
        PROHIBITION_SWTCH: 'N',
        RD_CHEQUE_AMOUNT: 0,
        RD_CHEQUE_SWITCH: 'N',
        REMARKS: ' ',
        SHORT_NAME: "Bob's ATF",
        SPEED_LMTR_EXEMPT: 'N',
        STATUS0: 40,
        SVA_MR_NO: ' ',
        TACHO_EXEMPT_MKR: 'N',
        TIMESTAMP0: 'sysdate',
        USER_ID: 'cvsvbin',
        VAT_REQUIRED: 0,
        VEHICLE_BOOKING_NO: 1,
        VEHICLE_CLASS: 'V',
        VRM: 'AB12CDE',
      };
    case 2:
      const trailerVtBooking = getMockVtBooking(2);
      return <VehicleBooking>{
        AXLE_SUPLM_AMT: 0,
        CANCELLATION_DATE: "to_date('0001-01-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss')",
        COMBI_NUM: 1,
        COUNTED_AXLES: 5,
        CUST_ACCT_PMNT_MKR: 1,
        DANG_GOODS_SWTCH: 'N',
        FEE_PAID: 0,
        FEE_REQUIRED: 0,
        FEE_UNDR_OVR_MRKR: 'N',
        FK_ACCT_ACCT_NO: '74926',
        FK_APPTYP_APPL_TYP: 'AAV',
        FK_BKGHDR2_NO: null,
        FK_BKGHDR2_USER_LO: null,
        FK_BKGHDR2_USER_NO: null,
        FK_BKGHDR_NO: 321,
        FK_BKGHDR_USER_LOC: 999,
        FK_BKGHDR_USER_NO: 'XR',
        FK_LANTBD_DATE: `to_date('${trailerVtBooking.testDate}', 'yyyy-mm-dd')`,
        FK_LANTBD_OPEN_TIM: `to_date('${trailerVtBooking.timeband.openTime}', 'yyyy-mm-dd hh24:mi:ss')`,
        FK_STATN_ID: 'P12345',
        FK_TBDPOS_ST_TIME: `to_date('${trailerVtBooking.testTime}', 'yyyy-mm-dd hh24:mi:ss')`,
        FK_TSLANE_NO: 6,
        FK_VEHBKG2_COMBI: null,
        FK_VEHBKG2_NO: null,
        FK_VEH_SYST_NO: 1234567,
        LOCN_SUPLM_AMT: 0,
        NO_OF_AXLES: 5,
        OOH_SUPLM_AMT: 0,
        OUT_OF_HOURS_MKR: 'N',
        PREV_FEE_SWTCH: 'Y',
        PROHIBITION_SWTCH: 'N',
        RD_CHEQUE_AMOUNT: 0,
        RD_CHEQUE_SWITCH: 'N',
        REMARKS: ' ',
        SHORT_NAME: "Bob's ATF",
        SPEED_LMTR_EXEMPT: 'N',
        STATUS0: 40,
        SVA_MR_NO: ' ',
        TACHO_EXEMPT_MKR: 'N',
        TIMESTAMP0: 'sysdate',
        USER_ID: 'cvsvbin',
        VAT_REQUIRED: 0,
        VEHICLE_BOOKING_NO: 1,
        VEHICLE_CLASS: 'V',
        VRM: 'TRAILER',
      };
    default:
      return <VehicleBooking>{};
  }
}
